project:
  type: book
  output-dir: docs
include-in-header: custom-head.html

book:
  title: "Heuristic Algorithms"
  author: "Pamela Schlosser"
  date: "12.1/2025"
  chapters:
    - index.qmd
    - algo.qmd
    - numpy.qmd
    - greedy.qmd
    - benchmark.qmd
    - es.qmd
    - hc.qmd
    - sa.qmd
    - ga.qmd
    - summary.qmd
    - references.qmd


format:
  html:
    css: styles.css
    number-sections: false 


editor: visual



